FROM nginx:alpine

#configuration
COPY ./nginx.conf /etc/nginx/nginx.conf

#content
COPY ./*.html /usr/share/nginx/html/
COPY ./css/*.css /usr/share/nginx/html/css/
COPY ./js/*.js /usr/share/nginx/html/js/
COPY ./lib/*.js /usr/share/nginx/html/lib/
COPY ./fonts/*.ttf /usr/share/nginx/html/fonts/
COPY ./assets/images/*.png /usr/share/nginx/html/assets/