version: "3"
services:
  web:
    image: nginx
    volumes:
     - ./client:/etc/nginx/templates
    ports:
     - "8080:80"
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80
  backend:
    build: .
    ports:
      - "9090:9090"